# Generated by Django 6.1.1 on 2026-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cloud_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('capacity_bytes', models.BigIntegerField(default=26843545600)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
