# Generated by Django 6.1.1 on 2026-09-04 06:49

import django.db.models.deletion
import guests.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('face_embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=guests.models.default_expiration)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='weddings.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_photos', to='guests.guest')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo')),
            ],
            options={
                'indexes': [models.Index(fields=['guest', 'confidence'], name='guests_phot_guest_i_44d3e9_idx')],
                'unique_together': {('photo', 'guest')},
            },
        ),
    ]
