# Generated by Django 6.1.1 on 2026-09-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cloudinary_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('display_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('HIDDEN', 'Hidden'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloudinary_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='accounts.cloudinaryaccount')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='weddings.wedding')),
            ],
            options={
                'indexes': [models.Index(fields=['wedding'], name='photos_phot_wedding_a710f5_idx'), models.Index(fields=['sha256'], name='photos_phot_sha256_0a3b79_idx'), models.Index(fields=['created_at'], name='photos_phot_created_84134a_idx'), models.Index(fields=['cloudinary_account'], name='photos_phot_cloudin_48d5a4_idx')],
                'unique_together': {('wedding', 'sha256')},
            },
        ),
    ]
