# Generated by Django 6.1.1 on 2026-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_options_cameraconnection_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconnection',
            name='active_folder',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='folder',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
