# Generated by Django 6.1.1 on 2026-09-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_cameraconnection_active_folder_photo_folder'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('local_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_usage_mb', models.FloatField(default=0.0)),
                ('ftp_status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=20)),
                ('queue_waiting', models.IntegerField(default=0)),
                ('queue_failed', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_devices', to='weddings.wedding')),
            ],
            options={
                'unique_together': {('wedding', 'device_id')},
            },
        ),
    ]
